//-------------------------------------------------
// sample
// This file was auto-generated by npsv 2015-11-11T14:39:13
//-------------------------------------------------
// W = 16, I = 8
	cpu_wr_task(0,0);  // 0.0
	cpu_wr_task(1,12);  // 0.1
	cpu_wr_task(2,25);  // 0.2
	cpu_wr_task(3,38);  // 0.3
	cpu_wr_task(4,51);  // 0.4
	cpu_wr_task(5,64);  // 0.5
	cpu_wr_task(6,76);  // 0.6
	cpu_wr_task(7,89);  // 0.7
	cpu_wr_task(8,102);  // 0.8
	cpu_wr_task(9,115);  // 0.9
	cpu_wr_task(10,128);  // 1.0
	cpu_wr_task(11,140);  // 1.1
	cpu_wr_task(12,153);  // 1.2
	cpu_wr_task(13,166);  // 1.3
	cpu_wr_task(14,179);  // 1.4
	cpu_wr_task(15,192);  // 1.5
	cpu_wr_task(16,204);  // 1.6
	cpu_wr_task(17,217);  // 1.7
	cpu_wr_task(18,230);  // 1.8
	cpu_wr_task(19,243);  // 1.9
	cpu_wr_task(20,256);  // 2.0
	cpu_wr_task(21,268);  // 2.1
	cpu_wr_task(22,281);  // 2.2
	cpu_wr_task(23,294);  // 2.3
	cpu_wr_task(24,307);  // 2.4
	cpu_wr_task(25,320);  // 2.5
	cpu_wr_task(26,332);  // 2.6
	cpu_wr_task(27,345);  // 2.7
	cpu_wr_task(28,358);  // 2.8
	cpu_wr_task(29,371);  // 2.9
	cpu_wr_task(30,384);  // 3.0
	cpu_wr_task(31,396);  // 3.1
	cpu_wr_task(32,409);  // 3.2
